### ISSUE TITLE
Feature request: Publish extension to open-vsx.org (VSCodium marketplace)

### ISSUE THREAD

**Issue by ccamara** [ActivityWatch/aw-watcher-vscode#16]
Currently, this extension cannot be installed from [VSCodium](https://vscodium.com/) interface, and it would be great to do so.
As far as I have read in VSCodium documentation (https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) there is a wiki documenting the process https://github.com/eclipse/openvsx/wiki/Publishing-Extensions 

Hope you could consider doing it.

**Comment by dentropy** [comment]
I just tried to manually install this extension in VSCodium via download from https://marketplace.visualstudio.com/items?itemName=lindraupe.aw-watcher-vscode

The following error was produced,

dentropy@MYPCNAME:~/Downloads$ codium --install-extension lindraupe.aw-watcher-vscode-0.4.1.vsix 
Installing extensions...
(node:24653) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'lindraupe.aw-watcher-vscode-0.4.1.vsix' was successfully installed.
Server returned 500

The extension show up in VSCodium but does not run. There is only the option to uninstall missing the disable button.

**Comment by brunoparga** [comment]
As a Codium user myself, I agree with @ccamara that the extension should be available to us. As @dentropy pointed out, there is an issue with direct installing the downloaded file, which I hope to have solved with #19 - input from both of you on whether the new version works for you would be greatly appreciated.

If we manage to sort @dentropy's issue, I will do my best to publish the file for this version on open-vsx.org (which I didn't know about, thank you!), assuming I can do that on behalf of the extension's developers.

**Comment by brunoparga** [comment]
@johan-bjareholt thank you for merging #19 . Now this issue here can be solved and make the extension more widely available!

I can and am willing to take most of the steps needed; however, it feels inappropriate for me to have ownership of the `ActivityWatch` namespace on OpenVsx, where the extension should be published. [This document](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace) details how you, or someone else officially affiliated with AW, would go about claiming ownership; I would be listed as a contributor. That might happen automatically due to my having created the namespace, or it might require you to manually add me. All of this is a one-time thing and wouldn't require ongoing attention from you.

Once that is in place, I'll send the new, working version of the extension to OpenVsx, if that all is alright with you.

**Comment by brunoparga** [comment]
@johan-bjareholt could I please get your thoughts on this? 🙂

**Comment by ErikBjare** [comment]
@brunoparga I'm getting to work on this right now, filed a claim for the namespace here: https://github.com/EclipseFdn/open-vsx.org/issues/355

**Comment by brunoparga** [comment]
@ErikBjare Thank you. I'll keep an eye out for both the approval of the claim and the version bump, to submit 0.5.0 once this is feasible (would also require me to be listed as a contributor account on OpenVsx).

**Comment by LennyPenny** [comment]
any update on the status of this?:)

**Comment by ErikBjare** [comment]
@brunoparga You have contributor access now, should be ready to deploy!

![image](https://user-images.githubusercontent.com/1405370/117011475-2baec500-acee-11eb-9854-f5d5502f271d.png)

**Comment by brunoparga** [comment]
Working on this today!

**Comment by ErikBjare** [comment]
Nice! I merged #25.

> Will future versions be auto-published to OpenVSX by CI/CD?

In the future that would be nice, but for now we'll publish manually.

**Comment by ErikBjare** [comment]
I added a link to the Open VSX listing in the README (https://open-vsx.org/extension/ActivityWatch/aw-watcher-vscode).

I think that's all, nice work @brunoparga! :1st_place_medal:
